### ISSUE TITLE
Globale SSID "Freifunk"

### ISSUE THREAD

**Issue by mojoaxel** [FreifunkFranken/ffff-next#1]
Es gibt momentan deutschlandweit Bestrebungen eine einheitliche SSID für die Access-Points zu verwendet. Das hat den Vorteil, das man sich, einmal mit dem Freifunk Netz verbunden, auch in anderen Städten automatisch verbindet.
Außerdem versucht man wohl etwas mehr die Marke zu pushen, jetzt wo es viel Kriegsberichterstattung und politisches Interesse gibt. 
Hier wäre es schön, wenn sich auch Franken beteiligen würde. Eine Firmware-Umstellung wäre da ein guter Zeitpunkt.

**Comment by kratz00** [comment]
Gibt es Quellen/Referenzen zu diesen Bestrebungen?

**Comment by mojoaxel** [comment]
[Die meisten Communities in NRW](https://twitter.com/Maltis/status/628099899184295937)
- [Aachen](http://freifunk-aachen.de/freifunk-fuer-gastronomie-handel-gewerbe-und-viele-mehr/)
- [Herbern](http://www.wa.de/lokales/herbern/freifunk-ortskern-kostenlose-internetverbindung-soll-allem-asylbewerbern-helfen-bergkamen-4959896.html)
- [Goettingen](https://freifunk-goettingen.de/2015/07/unser-netz-heisst-bald-einfach-freifunk/)
- [Münster](https://twitter.com/Freifunk_MS/status/600240391007424513), [Münsterland](https://freifunk-muensterland.de/am-20-mai-wird-freifunk-muenster-net-zu-freifunk/)

Hier eine allgemeine Diskussion*:
- https://forum.freifunk.net/t/ap-ssid-freifunk/110

\* _Ich übernehme keine Verantwortung für etwaige Hirnschädigungen durch Betrachtung des Freifunk-Forums_

**Comment by mojoaxel** [comment]
Ich hab mir diesbezüglich übrigens auch noch keine abschließende Meinung gebildet. Wollte aber mal eine Diskussion anregen.

**Comment by meskal** [comment]
Gerade in Franken halte ich das technisch f�r einen  eher schwierigen Weg. Wir 
betreiben mehrere unterschiedliche Netze mit unterschiedlichen IP-Ranges. Wenn 
ein Client von einem dieser Netze in ein anderes roamt, muss er wissen, dass 
er sich neue IP Adressen und Gateways holen muss. Das erkennt er (vermutlich 
unter anderem) an der SSID. Daher finde ich es aktuell eher einen Bug, dass 
wir unabh�ngig von der Hood, die gleiche SSID ausstrahlen. Das wollte ich 
eigentlich in der kommenden Firmware angehen und abh�ngig von der Hood 
entsprechend unterschiedliche SSIDs ausstrahlen. 

Das ist unter anderem gerade zwischen F�rth und N�rnberg wichtig, wo die 
beiden Hoods ja jeden Moment ineinander wachsen k�nnten. Ein Client der direkt 
zwischen N�rnberger und F�rther Hood wechselt, kann mit der neuen Verbindung 
dann nichts anfangen, da er davon ausgeht, das alte Gateway und die alte IP-
Adresse weiter verwenden zu k�nnen.

> Am 1. August 2015 14:18:21 MESZ, schrieb Alexander Wunschik
> notifications@github.com: Es gibt momentan deutschlandweit Bestrebungen 
> [1]
> eine einheitliche SSID f�r die Access-Points zu verwendet. Das hat den
> Vorteil, das man sich, einmal mit dem Freifunk Netz verbunden, auch in
> anderen St�dten automatisch verbindet. Au�erdem versucht man wohl etwas
> mehr die Marke zu pushen, jetzt wo es viel Kriegsberichterstattung und
> politisches Interesse gibt. Hier w�re es sch�n, wenn sich auch Franken
> beteiligen w�rde. Eine Firmware-Umstellung w�re da ein guter Zeitpunkt.
> 
> [1] [Die meisten Communities in
> NRW](https://twitter.com/Maltis/status/628099899184295937)
> 
> *
> [Aachen](http://freifunk-aachen.de/freifunk-fuer-gastronomie-handel-gewerbe
> -und-viele-mehr/) *
> [Herbern](http://www.wa.de/lokales/herbern/freifunk-ortskern-kostenlose-int
> ernetverbindung-soll-allem-asylbewerbern-helfen-bergkamen-4959896.html) *
> [Goettingen](https://freifunk-goettingen.de/2015/07/unser-netz-heisst-bald-> einfach-freifunk/) *
> [M�nster](https://twitter.com/Freifunk_MS/status/600240391007424513),
> [M�nsterland](https://freifunk-muensterland.de/am-20-mai-wird-freifunk-muen
> ster-net-zu-freifunk/)
> 
> Hier eine allgemeine Diskussion*:
> - https://forum.freifunk.net/t/ap-ssid-freifunk/110

**Comment by mojoaxel** [comment]
@meskal Danke für die ausführliche Antwort.
Ich dachte durch die Backbone-Struktur (interne Layer3-Vernetzung) wäre es auch nach einem Hood Wechseln möglich den momentan zugeordneten Gateway zu erreichen. IPv4 müssten doch eigentlich geroutet werden!? Solange die BSSID (Mesh) eine Hodd-Spezifischwe ID müsste das doch reichen? Wo liegt mein Denkfehler?

**Comment by meskal** [comment]
Du hast recht. Rechner aus Hood A können Rechner in Hood B erreichen. Das gilt 
aber nicht für Rechner, die von sich selber glauben sich noch in Hood B 
aufzuhalten. Die schicken dann nämlich Pakete mit einer Absenderadresse aus 
Hood B über die Hood A. FALLS so ein Paket noch in die Hood B geroutet wird, 
kommt es aber auf keinen Fall mehr zurück. Die Absenderadresse gehört ja zur 
Hood B, deswegen wird der Rechner(Gateway) in der Hood B versuchen das 
Antwortpaket in der Hood B zuzustellen. Das wird aber nicht klappen, da der 
Rechner mit dieser Adresse ja mittlerweile in Hood A ist und es nicht gemerkt 
hat.
Vielleicht übersehe ich da ja was, aber ich denke nicht, dass das klappt.

Am Dienstag, 11. August 2015, 03:41:02 schrieb Alexander Wunschik:

**Comment by mojoaxel** [comment]
Ok, die Verbindung zum Netz würde also quasi erhalten bleiben, bestehende Verbindungen aber abbrechen bei einem Hood-Wechsel. Das ist natürlich nicht das Verhalten, das man bei "Roaming" erwartet.

Ich denke damit ist diese Diskussion erstmal erledigt. Unter diesen Bedingungen sollten wir auch meiner Meinung nach lieber Hood-Spezifische SSIDs verwenden.
